# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('url_pattern', models.CharField(blank=True, default=None, help_text='Use "\\%s" where the value (Phone number, EMail address, ...) should be inserted.', max_length=200, null=True)),
                ('human_pattern', models.CharField(blank=True, default=None, help_text='Use "\\%s" where the value (Phone number, EMail address, ...) should be inserted.', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_manager.Contact')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_manager.ContactMethod')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_manager.ContactType'),
        ),
    ]
