# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoptions',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_to_option', to='contact_manager.Contact'),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_to_option', to='contact_manager.ContactMethod'),
        ),
    ]
