# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0003_auto_20161019_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactoptions',
            unique_together=set([('contact', 'method', 'value')]),
        ),
    ]
