# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0005_contact_is_memeber_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
    ]
