# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0007_auto_20161020_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoptions',
            name='url',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
